#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef DDLLSDK_SWIFT_H
#define DDLLSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DDLLSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS_NAMED("AdEventConfig")
@interface DDLLAdEventConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) DDLLAdEventConfig * _Nonnull sharedInstance;)
+ (DDLLAdEventConfig * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedInstance:(DDLLAdEventConfig * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@interface DDLLAdEventConfig (SWIFT_EXTENSION(DDLLSDK))
+ (void)parseConfig:(NSString * _Nullable)json;
@property (nonatomic, readonly) BOOL isEnable;
@end

@protocol GVTAd;
/// Base  delegate protocol. Common events for every ad object
SWIFT_PROTOCOL("_TtP7DDLLSDK14BaseAdDelegate_")
@protocol BaseAdDelegate
/// SDK calls this method when ad was successfully loaded
/// \param ad ad object that was loaded
///
- (void)didLoadWithAd:(id <GVTAd> _Nonnull)ad;
/// SDK calls this method when ad was not loaded for some reasons
/// \param ad ad object that was loaded
///
/// \param error the reason of failing loading
///
- (void)failToLoadWithAd:(id <GVTAd> _Nonnull)ad with:(NSError * _Nullable)error;
/// SDK calls this method when ad was shown on screen
/// \param ad ad object that was shown
///
- (void)didShowWithAd:(id <GVTAd> _Nonnull)ad;
/// SDK calls this method when ad fails to show for some reasons
/// \param ad ad object that was not shown
///
/// \param error the reason of failing loading
///
- (void)failToShowWithAd:(id <GVTAd> _Nonnull)ad with:(NSError * _Nullable)error;
/// SDK calls this method when ad was closed
/// \param ad ad object that was closed
///
- (void)didHideWithAd:(id <GVTAd> _Nonnull)ad;
/// SDK calls this method when user clicked on the ad
/// \param ad ad object that was clicked
///
- (void)didClickOn:(id <GVTAd> _Nonnull)ad;
@end

SWIFT_CLASS("_TtC7DDLLSDK11DDLLRequest")
@interface DDLLRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("DDZZConfig")
@interface DDLLConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, copy) NSString * _Nullable appKey;
@property (nonatomic, copy) NSString * _Nullable appSecret;
@property (nonatomic, copy) NSString * _Nullable umkAppId;
@property (nonatomic, copy) NSString * _Nullable afDevKey;
@property (nonatomic, copy) NSString * _Nullable iosAppId;
@property (nonatomic, copy) NSString * _Nullable oneLinkID;
@property (nonatomic, copy) NSString * _Nullable serverUrl;
@property (nonatomic, copy) NSString * _Nullable statUrl;
@property (nonatomic, copy) NSString * _Nullable adToken;
@property (nonatomic, copy) NSString * _Nullable adAppKey;
@property (nonatomic, copy) NSString * _Nullable adAppID;
@property (nonatomic, copy) NSString * _Nullable videoPlacementID;
@property (nonatomic, copy) NSString * _Nullable insPlacementID;
@property (nonatomic, copy) NSString * _Nullable openPlacementID;
@property (nonatomic, copy) NSString * _Nullable configType;
@property (nonatomic, copy) NSString * _Nullable networkNameStr;
@property (nonatomic, copy) NSString * _Nullable impressionCountAspect;
@property (nonatomic, copy) NSString * _Nullable insID;
@property (nonatomic, copy) NSString * _Nullable openID;
@property (nonatomic, copy) NSString * _Nullable videoID;
@property (nonatomic, copy) NSString * _Nullable bannerID;
/// 隐私协议
@property (nonatomic, copy) NSString * _Nullable privacyPolicyUri;
/// 用户团队协议
@property (nonatomic, copy) NSString * _Nullable termsOfServiceUri;
@property (nonatomic) NSInteger maxLoadPerDay;
@property (nonatomic) NSInteger maxLoadFailCount;
@property (nonatomic) NSInteger firstShow;
@property (nonatomic) double waterfallEcpm;
@property (nonatomic) NSInteger intervalShow;
@property (nonatomic) double defaultPrice;
@property (nonatomic) double floor;
@property (nonatomic) BOOL loadAfterClose;
@property (nonatomic) BOOL debug;
@property (nonatomic) BOOL printLog;
@end

@interface DDLLConfig (SWIFT_EXTENSION(DDLLSDK))
+ (DDLLConfig * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)toJson SWIFT_WARN_UNUSED_RESULT;
/// 通过 json 重新生成配置
+ (BOOL)loadConfig:(NSString * _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC7DDLLSDK9Databease")
@interface Databease : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Databease * _Nonnull sharedInstance;)
+ (Databease * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 准备工作
- (void)ready;
- (void)save;
@end

SWIFT_CLASS("_TtC7DDLLSDK8DevAdmin")
@interface DevAdmin : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7DDLLSDK14FirebaseRemote")
@interface FirebaseRemote : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FirebaseRemote * _Nonnull sharedInstance;)
+ (FirebaseRemote * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface FirebaseRemote (SWIFT_EXTENSION(DDLLSDK))
- (void)fetchWithComplete:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable))complete;
@end

/// Common protocol to every ad object.
SWIFT_PROTOCOL("_TtP7DDLLSDK5GVTAd_")
@protocol GVTAd
/// Call this method to start loading ad assets.
/// You will get notification in delegate object if ad was loaded successfully or failed to load,
/// \param bidResponse put bid response json string to load ad
///
- (void)loadWithBidResponse:(NSString * _Nonnull)bidResponse;
/// If you need to release resources implement this protocol and implement <code>destroy</code> function.
- (void)destroy;
/// Check whether ad is ready to be shown.
@property (nonatomic, readonly) BOOL isReady;
@property (nonatomic, readonly, copy) NSString * _Nonnull unitID;
@property (nonatomic, readonly) float amount;
- (void)addExtraParameterWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
@end

@class UIViewController;
SWIFT_CLASS("_TtC7DDLLSDK9GVTAdBase")
@interface GVTAdBase : NSObject
@property (nonatomic, strong) UIViewController * _Nullable fullscreenViewController;
@property (nonatomic, readonly, copy) NSString * _Nonnull unitID;
@property (nonatomic, readonly) float amount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)addExtraParameterWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
@end

/// Common protocol to every fullscreen ad.
SWIFT_PROTOCOL("_TtP7DDLLSDK15GVTFullscreenAd_")
@protocol GVTFullscreenAd <GVTAd>
/// Start showing ad after it was successfully loaded
/// \param viewController view controller that presents the ad
///
- (void)showFrom:(UIViewController * _Nonnull)viewController;
/// Start showing ad after it was successfully loaded
/// \param viewController view controller that presents the ad
///
/// \param muted mute video on start
///
- (void)showFrom:(UIViewController * _Nonnull)viewController muted:(BOOL)muted;
/// Fullscreen view controller
/// note:
/// This property is used to present fullscreen ads in SwiftUI
///
/// returns:
/// Fullscreen ad view controller
@property (nonatomic, readonly, strong) UIViewController * _Nullable fullscreenViewController;
@end

@interface GVTAdBase (SWIFT_EXTENSION(DDLLSDK)) <GVTFullscreenAd>
- (void)showFrom:(UIViewController * _Nonnull)viewController;
- (void)showFrom:(UIViewController * _Nonnull)viewController muted:(BOOL)muted;
@end

@interface GVTAdBase (SWIFT_EXTENSION(DDLLSDK)) <GVTAd>
- (void)loadWithBidResponse:(NSString * _Nonnull)bidResponse;
- (void)destroy;
@property (nonatomic, readonly) BOOL isReady;
@end

SWIFT_CLASS("_TtC7DDLLSDK12GVTAdManager")
@interface GVTAdManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) GVTAdManager * _Nonnull shared;)
+ (GVTAdManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull networkName;)
+ (NSString * _Nonnull)networkName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class GVTInitParams;
@interface GVTAdManager (SWIFT_EXTENSION(DDLLSDK))
/// Initializes GVTAdManager SDK
/// \param initParams Pass initialization params
///
/// \param completion this block is called when SDK initialization completes.
///
- (void)initializeWithInitParams:(GVTInitParams * _Nonnull)initParams configs:(NSDictionary<NSString *, NSString *> * _Nonnull)configs completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion SWIFT_AVAILABILITY(ios,introduced=13.0);
@end

/// GVT 配置类
SWIFT_CLASS_NAMED("GVTConfig")
@interface DDLLGVTConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DDLLGVTConfig * _Nonnull sharedInstance;)
+ (DDLLGVTConfig * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isEnable;
/// 顶层自定义系数(大于1.0的值)
@property (nonatomic, readonly) double topRate;
/// 底层自定义系数(小于1.0的值)
@property (nonatomic, readonly) double bottomRate;
/// 登陆国家
@property (nonatomic, copy) NSString * _Nonnull country;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface DDLLGVTConfig (SWIFT_EXTENSION(DDLLSDK))
/// 解析配置
- (void)parseConfig:(NSString * _Nullable)source;
/// 如果匹配不到国家，默认为 1.0
- (double)rateWithCountry:(NSString * _Nonnull)code SWIFT_WARN_UNUSED_RESULT;
/// 获取eCPM
- (double)defaultECPMWithCountry:(NSString * _Nonnull)code SWIFT_WARN_UNUSED_RESULT;
@end

/// Use this object to init GVTAdManager SDK
SWIFT_CLASS("_TtC7DDLLSDK13GVTInitParams")
@interface GVTInitParams : NSObject
/// Initializer for <code>GVTAdManagerInitParams</code> object.
/// \param appKey Use appKey from GVTAdManager dashboard
///
/// \param mediator In case of mediation integration set necessary value
///
- (nonnull instancetype)initWithAppKey:(NSString * _Nonnull)appKey mediator:(NSString * _Nonnull)mediator OBJC_DESIGNATED_INITIALIZER;
/// Calling this property directly is discouraged. Instead, convert an
/// instance of any type to a string by using the <code>String(describing:)</code>
/// initializer. This initializer works with any type, and uses the custom
/// <code>description</code> property for types that conform to
/// <code>CustomStringConvertible</code>:
/// \code
/// struct Point: CustomStringConvertible {
///     let x: Int, y: Int
///
///     var description: String {
///         return "(\(x), \(y))"
///     }
/// }
///
/// let p = Point(x: 21, y: 30)
/// let s = String(describing: p)
/// print(s)
/// // Prints "(21, 30)"
///
/// \endcodeThe conversion of <code>p</code> to a string in the assignment to <code>s</code> uses the
/// <code>Point</code> type’s <code>description</code> property.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol GVTInterstitialDelegate;
/// Fullscreen interstitial ad protocol.
SWIFT_PROTOCOL("_TtP7DDLLSDK15GVTInterstitial_")
@protocol GVTInterstitial <GVTFullscreenAd>
/// Set delegate to be notified of when your ad is ready and of other ad-related events.
@property (nonatomic, strong) id <GVTInterstitialDelegate> _Nullable interstitialDelegate;
@end

SWIFT_CLASS("_TtC7DDLLSDK17GVTInterstitialAd")
@interface GVTInterstitialAd : GVTAdBase
@property (nonatomic, weak) id <GVTInterstitialDelegate> _Nullable interstitialDelegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface GVTInterstitialAd (SWIFT_EXTENSION(DDLLSDK)) <GVTInterstitial>
- (void)destroy;
@end

/// Rewarded interstitial delegate protocol. Implement it to get notified interstitial ad events.
SWIFT_PROTOCOL("_TtP7DDLLSDK23GVTInterstitialDelegate_")
@protocol GVTInterstitialDelegate <BaseAdDelegate>
@end

SWIFT_CLASS("_TtC7DDLLSDK10GVTManager")
@interface GVTManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) GVTManager * _Nonnull shared;)
+ (GVTManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull supportAdTypes;)
+ (NSArray<NSString *> * _Nonnull)supportAdTypes SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)activate;
@end

@protocol GVTNativeDelegate;
@protocol GVTNativeAssests;
SWIFT_PROTOCOL("_TtP7DDLLSDK9GVTNative_")
@protocol GVTNative <GVTAd>
@property (nonatomic, strong) id <GVTNativeDelegate> _Nullable delegate;
@property (nonatomic, readonly, strong) id <GVTNativeAssests> _Nullable assets;
- (void)handleClick;
- (void)handleImpression;
@end

@class UIImage;
@class UIView;
SWIFT_PROTOCOL("_TtP7DDLLSDK16GVTNativeAssests_")
@protocol GVTNativeAssests
@property (nonatomic, readonly, strong) UIImage * _Nullable appIcon;
@property (nonatomic, readonly, strong) UIImage * _Nullable mainImage;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull sponsorText;
@property (nonatomic, readonly, copy) NSString * _Nonnull ctaTitle;
@property (nonatomic, readonly) double rating;
@property (nonatomic, readonly, strong) UIView * _Nullable videoView;
@end

SWIFT_PROTOCOL("_TtP7DDLLSDK17GVTNativeDelegate_")
@protocol GVTNativeDelegate <BaseAdDelegate>
@optional
/// SDK calls this method when Native ad click handle request is completed
/// \param ad ad object for which click request was handled.
///
- (void)didHandleClickWithAd:(id <GVTAd> _Nonnull)ad;
/// SDK calls this method when Native ad impression handle request is completed
/// \param ad ad object for which impression request was handled.
///
- (void)didHandleImpressionWithAd:(id <GVTAd> _Nonnull)ad;
@end

@protocol GVTRewardedDelegate;
/// Fullscreen rewarded interstitial ad protocol.
SWIFT_PROTOCOL("_TtP7DDLLSDK11GVTRewarded_")
@protocol GVTRewarded <GVTFullscreenAd>
/// Set delegate to be notified of when your ad is ready and of other ad-related events.
@property (nonatomic, strong) id <GVTRewardedDelegate> _Nullable rewardedDelegate;
@end

SWIFT_CLASS("_TtC7DDLLSDK13GVTRewardedAd")
@interface GVTRewardedAd : GVTAdBase
@property (nonatomic, weak) id <GVTRewardedDelegate> _Nullable rewardedDelegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface GVTRewardedAd (SWIFT_EXTENSION(DDLLSDK)) <GVTRewarded>
- (void)destroy;
@end

/// Rewarded interstitial delegate protocol. Implement it to get notified rewarded ad events.
SWIFT_PROTOCOL("_TtP7DDLLSDK19GVTRewardedDelegate_")
@protocol GVTRewardedDelegate <BaseAdDelegate>
/// SDK calls this method when the user gets a reward.
/// \param ad ad object that produce reward
///
- (void)userRewardedWithAd:(id <GVTAd> _Nonnull)ad;
/// SDK calls this method when video starts.
/// Optional, it can be not invoked.
/// \param ad ad object that starts video.
///
- (void)rewardedVideoStartedWithAd:(id <GVTAd> _Nonnull)ad;
/// SDK calls this method when the video has completed video playback.
/// Optional, it can be not invoked.
/// \param ad ad object that video reached the end.
///
- (void)rewardedVideoCompletedWithAd:(id <GVTAd> _Nonnull)ad;
@end

/// IDFA 权限申请
SWIFT_CLASS("_TtC7DDLLSDK11IDFARequest")
@interface IDFARequest : NSObject
+ (void)trackingWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 本地缓存统一管理类
SWIFT_CLASS_NAMED("LocalCache")
@interface DDLLLocalCache : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DDLLLocalCache * _Nonnull sharedInstance;)
+ (DDLLLocalCache * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// true = 已缓存有用户分层信息
@property (nonatomic) BOOL hasUserTierInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 用于测试
SWIFT_CLASS("_TtC7DDLLSDK11ManagerTest")
@interface ManagerTest : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ManagerTest * _Nonnull shared;)
+ (ManagerTest * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ManagerTest (SWIFT_EXTENSION(DDLLSDK))
- (void)activate;
@end

/// 全局内存缓存统一管理类
SWIFT_CLASS_NAMED("MemoryCache")
@interface DDLLLMemoryCache : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DDLLLMemoryCache * _Nonnull sharedInstance;)
+ (DDLLLMemoryCache * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// 标志当前解析配置是否为 FirstMediation
/// true = 表示当前解析的配置为FirstMediation
@property (nonatomic) BOOL isFirstMediation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface NSObject (SWIFT_EXTENSION(DDLLSDK))
/// 对象转 JSON字符串
- (NSString * _Nullable)jsonString SWIFT_WARN_UNUSED_RESULT;
@end

@interface NSString (SWIFT_EXTENSION(DDLLSDK))
/// JSON 字符串转对象
- (id _Nullable)toObject SWIFT_WARN_UNUSED_RESULT;
/// JSON 字符串转数组对象
- (NSArray * _Nullable)jsonArray SWIFT_WARN_UNUSED_RESULT;
/// JSON 字符串转字典对象
- (NSDictionary<NSString *, id> * _Nullable)jsonDictionary SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("PreGeneralConfig")
@interface DDLLLPreGeneralConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) DDLLLPreGeneralConfig * _Nonnull shared;)
+ (DDLLLPreGeneralConfig * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(DDLLLPreGeneralConfig * _Nonnull)value;
/// AppLovin(Max SDK) 增加控制参数用于控制广告加载失败重试，缓存
@property (nonatomic, copy) NSArray<NSString *> * _Nullable disableMaxAutoRetryUnitIDs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface DDLLLPreGeneralConfig (SWIFT_EXTENSION(DDLLSDK))
+ (void)loadWithFrom:(NSString * _Nullable)json;
+ (BOOL)isValidMaxAutoRetryUnitID:(NSString * _Nullable)unitID SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("ReachabilityChanged")
@interface DDLLLReachabilityChanged : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DDLLLReachabilityChanged * _Nonnull sharedInstance;)
+ (DDLLLReachabilityChanged * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable listenNetworkReachabilityChange)(void);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;
SWIFT_CLASS_NAMED("SDKBundle")
@interface DDLLBundle : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull main;)
+ (NSBundle * _Nonnull)main SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 获取 SIM 信息
SWIFT_CLASS("_TtC7DDLLSDK11SimCardInfo")
@interface SimCardInfo : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SimCardInfo (SWIFT_EXTENSION(DDLLSDK))
/// 获取 Sim Card 所有 MCC
+ (NSArray<NSString *> * _Nonnull)mccs SWIFT_WARN_UNUSED_RESULT;
/// 获取 Sim Card 所有网络国家代码
+ (NSArray<NSString *> * _Nonnull)iccs SWIFT_WARN_UNUSED_RESULT;
@end

/// 智能瀑布流频控管理类
SWIFT_CLASS_NAMED("SmartRateLimiter")
@interface DDLLSmartRateLimiter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface DDLLSmartRateLimiter (SWIFT_EXTENSION(DDLLSDK))
/// 配置参数
+ (void)configWithLoadInterval:(NSInteger)loadInterval loadAdCount:(NSInteger)loadAdCount;
/// 记录广告请求时间
+ (void)addRecord:(NSString * _Nonnull)adType;
/// 判断是否达到限制
/// @Return true = 达到限制
+ (BOOL)isReachLimit:(NSString * _Nonnull)adType SWIFT_WARN_UNUSED_RESULT;
@end

/// 智能瀑布流状态配置类
SWIFT_CLASS_NAMED("SmartStateConfig")
@interface DDLLSmartStateConfig : NSObject
/// 标志广告是否正在加载中
@property (nonatomic) BOOL isLoading;
/// ecpm
@property (nonatomic) double price;
/// 标志是否是第一次加载
@property (nonatomic) BOOL isFirstLoad;
/// ecpm 最后一次更新时间(秒)
@property (nonatomic) double lastPriceUpdateTime;
/// 最后一次成功加载广告的时间(秒)
@property (nonatomic) double lastLoadedTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)resetLastLoadedTime;
+ (DDLLSmartStateConfig * _Nonnull)fetch:(NSString * _Nonnull)adType adPlatform:(NSString * _Nonnull)adPlatform SWIFT_WARN_UNUSED_RESULT;
@end

@class NSCoder;
/// 虚拟广告显示控制器
SWIFT_CLASS_NAMED("TestAdViewController")
@interface DDLLTestAdViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@interface DDLLTestAdViewController (SWIFT_EXTENSION(DDLLSDK))
+ (void)showWithTag:(NSString * _Nonnull)tag onCloseAction:(void (^ _Nonnull)(void))onCloseAction onClickAction:(void (^ _Nonnull)(void))onClickAction;
+ (void)showGVTOnCloseAction:(void (^ _Nonnull)(void))onCloseAction onClickAction:(void (^ _Nonnull)(void))onClickAction;
@end

/// iOS 设备温度变化监测(不能具体到某个温度，只是到某个级别)
SWIFT_CLASS_NAMED("ThermalState")
@interface DDLLThermalState : NSObject
+ (void)start;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Unity 通信管理
SWIFT_CLASS("_TtC7DDLLSDK12UnityChannel")
@interface UnityChannel : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UnityChannel * _Nonnull sharedInstance;)
+ (UnityChannel * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface UnityChannel (SWIFT_EXTENSION(DDLLSDK))
+ (NSString * _Nonnull)channelName SWIFT_WARN_UNUSED_RESULT;
/// 接收来自Unity的消息
- (void)receiveWithData:(NSString * _Nonnull)data;
@end

SWIFT_CLASS_NAMED("Version")
@interface DDLLVersion : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull name;)
+ (NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull code;)
+ (NSString * _Nonnull)code SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
